#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m space 1 --layout stack

yabai -m rule --add app="^(Microsoft Outlook|Microsoft Teams)$" space=1
yabai -m rule --add app="^(Android Studio|Alacritty|Wezterm)$" space=2
yabai -m rule --add app="^(Zoom)$" space=3
yabai -m rule --add app="^Firefox$" space=4
yabai -m rule --add app="^Google Chrome$" space=5

echo "yabai configuration loaded.."
