build *args='':
  ./abt -v build {{args}}

publish module:
  IS_DOCKER_ENV=1 ./abt -v build -p {{module}} publishModule

install arch='':
  cd projects/fulcrum/
  {{ if arch == "x86" { "INSTRUMENT_TEST=1" } else { "" } }} ./gradlew :app:instGNPD

startavd name='@Pixel_2_API_R':
  $ANDROID_SDK_ROOT/emulator/emulator -no-skin -no-audio {{name}} > /dev/null 2>&1

push story_no:
  git push origin @:refs/heads/story/PAMPP-{{story_no}}

fetch branch='main':
  git fetch origin {{branch}}

reset branch='main':
  git reset --hard origin/{{branch}}

pr:
  gh pr status

merge pr_no:
  gh pr merge -s -d {{pr_no}}

view pr_no:
  gh pr view -w {{pr_no}}

review query='user-review-requested:@me':
  for pr in $(gh pr list --search {{query}} --json number --jq '.[].number'); do \
      gh pr view -w $pr; \
  done

