[general]
import = ["local.toml"]

[cursor]
[cursor.style]
blinking = "On"
shape = "Beam"

[cursor.vi_mode_style]
blinking = "On"
shape = "Underline"

[font]
size = 16.0
[font.normal]
family = "Hack Nerd Font Mono"

[[hints.enabled]]
action = "Copy"
hyperlinks = true
persist = false
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true

[window]
decorations = "None"
dynamic_title = true
opacity = 0.9
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
